<x-head :includeLegal='true'></x-head>

<body>
    <header>
        <div>
            <h1>@lang('legal_notice.title')</h1>
            <p>@lang('legal_notice.update')</p>
        </div>
    </header>
    <main>
        <section>
            <h2>@lang('legal_notice.editor.title')</h2>
            <div>
                <p>@lang('legal_notice.editor.1')</p>
                <p>@lang('legal_notice.editor.2')</p>
                <p>@lang('legal_notice.editor.3')</p>
                <p>@lang('legal_notice.editor.4')</p>
                <p>@lang('legal_notice.editor.5')</p>
            </div>
        </section>
        <section>
            <h2>@lang('legal_notice.hosting.title')</h2>
            <div>
                <p>@lang('legal_notice.hosting.1')</p>
                <p>@lang('legal_notice.hosting.2')</p>
                <p>@lang('legal_notice.hosting.3')</p>
                <p>@lang('legal_notice.hosting.4')</p>
                <p>@lang('legal_notice.hosting.5')</p>
                <p>@lang('legal_notice.hosting.6')</p>
            </div>
        </section>
        <section>
            <h2>@lang('legal_notice.intellectual_property.title')</h2>
            <div>
                <p>@lang('legal_notice.intellectual_property.1')</p>
                <p>@lang('legal_notice.intellectual_property.2')</p>
                <p>@lang('legal_notice.intellectual_property.3')</p>
                <p>@lang('legal_notice.intellectual_property.4')</p>
                <p>@lang('legal_notice.intellectual_property.5')</p>
                <p>@lang('legal_notice.intellectual_property.6')</p>
                <p>@lang('legal_notice.intellectual_property.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('legal_notice.responsibility.title')</h2>
            <div>
                <p>@lang('legal_notice.responsibility.1')</p>
                <p>@lang('legal_notice.responsibility.2')</p>
                <p>@lang('legal_notice.responsibility.3')</p>
                <p>@lang('legal_notice.responsibility.4')</p>
                <p>@lang('legal_notice.responsibility.5')</p>
                <p>@lang('legal_notice.responsibility.6')</p>
                <p>@lang('legal_notice.responsibility.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('legal_notice.personal_data.title')</h2>
            <div>
                <p>@lang('legal_notice.personal_data.1')</p>
                <p>@lang('legal_notice.personal_data.2')</p>
                <p>@lang('legal_notice.personal_data.3')</p>
                <p>@lang('legal_notice.personal_data.4')</p>
                <p>@lang('legal_notice.personal_data.5')</p>
                <p>@lang('legal_notice.personal_data.6')</p>
                <p>@lang('legal_notice.personal_data.7')</p>
                <p>@lang('legal_notice.personal_data.8')</p>
            </div>
        </section>
        <section>
            <h2>@lang('legal_notice.hyperlinks.title')</h2>
            <div>
                <p>@lang('legal_notice.hyperlinks.1')</p>
                <p>@lang('legal_notice.hyperlinks.2')</p>
                <p>@lang('legal_notice.hyperlinks.3')</p>
                <p>@lang('legal_notice.hyperlinks.4')</p>
                <p>@lang('legal_notice.hyperlinks.5')</p>
            </div>
        </section>
        <section>
            <h2>@lang('legal_notice.law_and_jurisdiction.title')</h2>
            <div>
                <p>@lang('legal_notice.law_and_jurisdiction.1')</p>
                <p>@lang('legal_notice.law_and_jurisdiction.2')</p>
                <p>@lang('legal_notice.law_and_jurisdiction.3')</p>
                <p>@lang('legal_notice.law_and_jurisdiction.4')</p>
                <p>@lang('legal_notice.law_and_jurisdiction.5')</p>
                <p>@lang('legal_notice.law_and_jurisdiction.6')</p>
            </div>
        </section>
    </main>
    <footer>
        <p>@lang('legal_notice.contact')<span>juleslejeunepro@gmail.com</span></p>
        <p>@lang('legal_notice.accept')</p>
    </footer>
</body>

</html>
