<x-head :includeLegal='true'></x-head>

<body>
    <header>
        <div>
            <h1>@lang('privacy.title')</h1>
            <p>@lang('privacy.update')</p>
        </div>
    </header>
    <main>
        <section>
            <h2>@lang('privacy.introduction.title')</h2>
            <div>
                <p>@lang('privacy.introduction.1')</p>
                <p>@lang('privacy.introduction.2')</p>
                <p>@lang('privacy.introduction.3')</p>
                <p>@lang('privacy.introduction.4')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.data_collected.title')</h2>
            <div>
                <p>@lang('privacy.data_collected.1')</p>
                <p>@lang('privacy.data_collected.2')</p>
                <p>@lang('privacy.data_collected.3')</p>
                <p>@lang('privacy.data_collected.4')</p>
                <p>@lang('privacy.data_collected.5')</p>
                <p>@lang('privacy.data_collected.6')</p>
                <p>@lang('privacy.data_collected.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.data_usage.title')</h2>
            <div>
                <p>@lang('privacy.data_usage.1')</p>
                <p>@lang('privacy.data_usage.2')</p>
                <p>@lang('privacy.data_usage.3')</p>
                <p>@lang('privacy.data_usage.4')</p>
                <p>@lang('privacy.data_usage.5')</p>
                <p>@lang('privacy.data_usage.6')</p>
                <p>@lang('privacy.data_usage.7')</p>
                <p>@lang('privacy.data_usage.8')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.data_sharing.title')</h2>
            <div>
                <p>@lang('privacy.data_sharing.1')</p>
                <p>@lang('privacy.data_sharing.2')</p>
                <p>@lang('privacy.data_sharing.3')</p>
                <p>@lang('privacy.data_sharing.4')</p>
                <p>@lang('privacy.data_sharing.5')</p>
                <p>@lang('privacy.data_sharing.6')</p>
                <p>@lang('privacy.data_sharing.7')</p>
                <p>@lang('privacy.data_sharing.8')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.data_security.title')</h2>
            <div>
                <p>@lang('privacy.data_security.1')</p>
                <p>@lang('privacy.data_security.2')</p>
                <p>@lang('privacy.data_security.3')</p>
                <p>@lang('privacy.data_security.4')</p>
                <p>@lang('privacy.data_security.5')</p>
                <p>@lang('privacy.data_security.6')</p>
                <p>@lang('privacy.data_security.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.data_retention.title')</h2>
            <div>
                <p>@lang('privacy.data_retention.1')</p>
                <p>@lang('privacy.data_retention.2')</p>
                <p>@lang('privacy.data_retention.3')</p>
                <p>@lang('privacy.data_retention.4')</p>
                <p>@lang('privacy.data_retention.5')</p>
                <p>@lang('privacy.data_retention.6')</p>
                <p>@lang('privacy.data_retention.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.user_law.title')</h2>
            <div>
                <p>@lang('privacy.user_law.1')</p>
                <p>@lang('privacy.user_law.2')</p>
                <p>@lang('privacy.user_law.3')</p>
                <p>@lang('privacy.user_law.4')</p>
                <p>@lang('privacy.user_law.5')</p>
                <p>@lang('privacy.user_law.6')</p>
                <p>@lang('privacy.user_law.7')</p>
                <p>@lang('privacy.user_law.8')</p>
                <p>@lang('privacy.user_law.9')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.cookies.title')</h2>
            <div>
                <p>@lang('privacy.cookies.1')</p>
                <p>@lang('privacy.cookies.2')</p>
                <p>@lang('privacy.cookies.3')</p>
                <p>@lang('privacy.cookies.4')</p>
                <p>@lang('privacy.cookies.5')</p>
                <p>@lang('privacy.cookies.6')</p>
                <p>@lang('privacy.cookies.7')</p>
                <p>@lang('privacy.cookies.8')</p>
                <p>@lang('privacy.cookies.9')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.policy_changes.title')</h2>
            <div>
                <p>@lang('privacy.policy_changes.1')</p>
                <p>@lang('privacy.policy_changes.2')</p>
                <p>@lang('privacy.policy_changes.3')</p>
                <p>@lang('privacy.policy_changes.4')</p>
                <p>@lang('privacy.policy_changes.5')</p>
                <p>@lang('privacy.policy_changes.6')</p>
                <p>@lang('privacy.policy_changes.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('privacy.contacts.title')</h2>
            <div>
                <p>@lang('privacy.contacts.1')</p>
                <p>@lang('privacy.contacts.2')</p>
                <p>@lang('privacy.contacts.3')</p>
                <p>@lang('privacy.contacts.4')</p>
                <p>@lang('privacy.contacts.5')</p>
                <p>@lang('privacy.contacts.6')</p>
            </div>
        </section>
    </main>
    <footer>
        <p>@lang('privacy.contact')<span>juleslejeunepro@gmail.com</span></p>
        <p>@lang('privacy.accept')</p>
    </footer>
</body>

</html>
