<x-head :includeLegal='true'></x-head>

<body>
    <header>
        <div>
            <h1>@lang('terms.title')</h1>
            <p>@lang('terms.update')</p>
        </div>
    </header>
    <main>
        <section>
            <h2>@lang('terms.preamble.title')</h2>
            <div>
                <p>@lang('terms.preamble.paragraph.1')</p>
                <p>@lang('terms.preamble.paragraph.2')</p>
                <p>@lang('terms.preamble.paragraph.3')</p>
                <p>@lang('terms.preamble.paragraph.4')</p>
                <p>@lang('terms.preamble.paragraph.5')</p>
                <ul>
                    <p>@lang('terms.preamble.paragraph.6.title')</p>
                    <li>@lang('terms.preamble.paragraph.6.1')</li>
                    <li>@lang('terms.preamble.paragraph.6.2')</li>
                    <li>@lang('terms.preamble.paragraph.6.3')</li>
                </ul>
                <p>@lang('terms.preamble.paragraph.7')</p>
                <p>@lang('terms.preamble.paragraph.8')</p>
                <p>@lang('terms.preamble.paragraph.9')</p>
                <p>@lang('terms.preamble.paragraph.10')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.définition.title')</h2>
            <div>
                <p>@lang('terms.définition.1')</p>
                <p>@lang('terms.définition.2')</p>
                <p>@lang('terms.définition.3')</p>
                <p>@lang('terms.définition.4')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.object.title')</h2>
            <div>
                <p>@lang('terms.object.1')</p>
                <p>@lang('terms.object.2')</p>
                <p>@lang('terms.object.3')</p>
                <p>@lang('terms.object.4')</p>
                <p>@lang('terms.object.5')</p>
                <p>@lang('terms.object.6')</p>
                <p>@lang('terms.object.7')</p>
                <p>@lang('terms.object.8')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.access.title')</h2>
            <div>
                <p>@lang('terms.access.1')</p>
                <p>@lang('terms.access.2')</p>
                <p>@lang('terms.access.3')</p>
                <p>@lang('terms.access.4')</p>
                <p>@lang('terms.access.5')</p>
                <p>@lang('terms.access.6')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.inscription.title')</h2>
            <div>
                <p>@lang('terms.inscription.1')</p>
                <p>@lang('terms.inscription.2')</p>
                <p>@lang('terms.inscription.3')</p>
                <p>@lang('terms.inscription.4')</p>
                <p>@lang('terms.inscription.5')</p>
                <p>@lang('terms.inscription.6')</p>
                <p>@lang('terms.inscription.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.services.title')</h2>
            <div>
                <p>@lang('terms.services.1')</p>
                <p>@lang('terms.services.2')</p>
                <p>@lang('terms.services.3')</p>
                <p>@lang('terms.services.4')</p>
                <p>@lang('terms.services.5')</p>
                <p>@lang('terms.services.6')</p>
                <p>@lang('terms.services.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.obligation_data.title')</h2>
            <div>
                <p>@lang('terms.obligation_data.1')</p>
                <p>@lang('terms.obligation_data.2')</p>
                <p>@lang('terms.obligation_data.3')</p>
                <p>@lang('terms.obligation_data.4')</p>
                <p>@lang('terms.obligation_data.5')</p>
                <p>@lang('terms.obligation_data.6')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.ownership.title')</h2>
            <div>
                <p>@lang('terms.ownership.1')</p>
                <p>@lang('terms.ownership.2')</p>
                <p>@lang('terms.ownership.3')</p>
                <p>@lang('terms.ownership.4')</p>
                <p>@lang('terms.ownership.5')</p>
                <p>@lang('terms.ownership.6')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.responsibility.title')</h2>
            <div>
                <p>@lang('terms.responsibility.1')</p>
                <p>@lang('terms.responsibility.2')</p>
                <p>@lang('terms.responsibility.3')</p>
                <p>@lang('terms.responsibility.4')</p>
                <p>@lang('terms.responsibility.5')</p>
                <p>@lang('terms.responsibility.6')</p>
                <p>@lang('terms.responsibility.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.modifications.title')</h2>
            <div>
                <p>@lang('terms.modifications.1')</p>
                <p>@lang('terms.modifications.2')</p>
                <p>@lang('terms.modifications.3')</p>
                <p>@lang('terms.modifications.4')</p>
                <p>@lang('terms.modifications.5')</p>
                <p>@lang('terms.modifications.6')</p>
                <p>@lang('terms.modifications.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.law.title')</h2>
            <div>
                <p>@lang('terms.law.1')</p>
                <p>@lang('terms.law.2')</p>
                <p>@lang('terms.law.3')</p>
                <p>@lang('terms.law.4')</p>
                <p>@lang('terms.law.5')</p>
                <p>@lang('terms.law.6')</p>
                <p>@lang('terms.law.7')</p>
            </div>
        </section>
        <section>
            <h2>@lang('terms.disposition.title')</h2>
            <div>
                <p>@lang('terms.disposition.1')</p>
                <p>@lang('terms.disposition.2')</p>
                <p>@lang('terms.disposition.3')</p>
                <p>@lang('terms.disposition.4')</p>
                <p>@lang('terms.disposition.5')</p>
            </div>
        </section>
    </main>
    <footer>
        <p>@lang('terms.contact')<span>juleslejeunepro@gmail.com</span></p>
        <p>@lang('terms.accept')</p>
    </footer>
</body>

</html>
